server:
  http: "\${SERVER_PORT:8080}"

spring:
  application:
    name: ${artifactId}
    version: ${version}
  jmx.enabled: true
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: "\${SHOW_SQL:false}"
    hibernate:
      ddl-auto: none
  datasource:
    url: "\${ANALYTICS_DB_URL:jdbc:postgresql://\${ANALYTICS_DB_HOST:localhost}:\${ANALYTICS_DB_PORT:5432}/\${ANALYTICS_DB_NAME:analytics}?currentSchema=raw}"
    username: "\${ANALYTICS_DB_USER}"
    password: "\${ANALYTICS_DB_PASSWORD}"
    driverClassName: org.postgresql.Driver
  temporal:
    namespace: "\${TEMPORAL_SERVER_NAMESPACE:pu-analytics}"
    connection:
      enable-https: "\${TEMPORAL_SERVER_ENABLE_HTTPS:false}"
      target: "\${TEMPORAL_SERVER_HOST:localhost}:\${TEMPORAL_SERVER_PORT:7233}"
    workers-auto-discovery:
      packages:
        - it.gov.pagopa.analytics.ingestion.wf
    workers:
      # generic
      - task-queue: DataIngestionWF
        capacity:
          workflow-task-pollers-configuration:
            poller-behavior-autoscaling:
              enabled: true
              initial-concurrent-task-pollers: "\${WF_DATA_INGESTION_MIN_POLLER_SIZE:1}"
              min-concurrent-task-pollers: "\${WF_DATA_INGESTION_MIN_POLLER_SIZE:1}"
              max-concurrent-task-pollers: "\${WF_DATA_INGESTION_MAX_POLLER_SIZE:3}"
          activity-task-pollers-configuration:
            poller-behavior-autoscaling:
              enabled: true
              initial-concurrent-task-pollers: "\${ACTIVITY_DATA_INGESTION_MIN_POLLER_SIZE:1}"
              min-concurrent-task-pollers: "\${ACTIVITY_DATA_INGESTION_MIN_POLLER_SIZE:1}"
              max-concurrent-task-pollers: "\${ACTIVITY_DATA_INGESTION_MAX_POLLER_SIZE:3}"
  cloud:
    function:
      definition: paymentsConsumer;dataEventsConsumer;auditConsumer
    stream:
      binders:
        kafka-payments-consumer:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: "\${KAFKA_PAYMENTS_BINDER_BROKER:\${KAFKA_BINDER_BROKER:}}"
              configuration:
                client.id: analyticsingestion-paymentsConsumer
                sasl.jaas.config: "\${KAFKA_PAYMENTS_CONSUMER_SASL_JAAS_CONFIG:}"
        kafka-data-events-consumer:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: "\${KAFKA_DATA_EVENTS_BINDER_BROKER:\${KAFKA_BINDER_BROKER:}}"
              configuration:
                client.id: analyticsingestion-dataEventsConsumer
                sasl.jaas.config: "\${KAFKA_DATA_EVENTS_CONSUMER_SASL_JAAS_CONFIG:}"
        kafka-audit-consumer:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: "\${KAFKA_AUDIT_BINDER_BROKER:\${KAFKA_BINDER_BROKER:}}"
              configuration:
                client.id: analyticsingestion-auditConsumer
                sasl.jaas.config: "\${KAFKA_AUDIT_CONSUMER_SASL_JAAS_CONFIG:}"
      bindings:
        paymentsConsumer-in-0:
          binder: kafka-payments-consumer
          content-type: "\${KAFKA_CONTENT_TYPE:application/json}"
          destination: "\${KAFKA_TOPIC_PAYMENTS:p4pa-payhub-payments-evh}"
          group: "\${KAFKA_PAYMENTS_GROUP_ID:analytics-payments-consumer-group}"
          consumer:
            auto-startup: "\${KAFKA_PAYMENTS_CONSUMER_ENABLED:true}"
            concurrency: "\${KAFKA_PAYMENTS_CONSUMER_CONCURRENCY:1}"
        dataEventsConsumer-in-0:
          binder: kafka-data-events-consumer
          content-type: "\${KAFKA_CONTENT_TYPE:application/json}"
          destination: "\${KAFKA_TOPIC_DATA_EVENTS:p4pa-payhub-data-events-evh}"
          group: "\${KAFKA_DATA_EVENTS_GROUP_ID:analytics-data-events-consumer-group}"
          consumer:
            auto-startup: "\${KAFKA_DATA_EVENTS_CONSUMER_ENABLED:true}"
            concurrency: "\${KAFKA_DATA_EVENTS_CONSUMER_CONCURRENCY:1}"
        auditConsumer-in-0:
          binder: kafka-audit-consumer
          content-type: "\${KAFKA_CONTENT_TYPE:application/json}"
          destination: "\${KAFKA_TOPIC_AUDIT:p4pa-payhub-audit-evh}"
          group: "\${KAFKA_AUDIT_GROUP_ID:analytics-audit-consumer-group}"
          consumer:
            auto-startup: "\${KAFKA_AUDIT_CONSUMER_ENABLED:true}"
            concurrency: "\${KAFKA_AUDIT_CONSUMER_CONCURRENCY:1}"
      kafka:
        binder:
          auto-create-topics: false
          configuration:
            heartbeat.interval.ms: "\${KAFKA_CONFIG_HEARTBEAT_INTERVAL_MS:3000}"
            session.timeout.ms: "\${KAFKA_CONFIG_SESSION_TIMEOUT_MS:30000}"
            request.timeout.ms: "\${KAFKA_CONFIG_REQUEST_TIMEOUT_MS:60000}"
            metadata.max.age.ms: "\${KAFKA_CONFIG_METADATA_MAX_AGE:180000}"
            sasl.mechanism: "\${KAFKA_CONFIG_SASL_MECHANISM:PLAIN}"
            security.protocol: "\${KAFKA_CONFIG_SECURITY_PROTOCOL:SASL_SSL}"
            max.request.size: "\${KAFKA_CONFIG_MAX_REQUEST_SIZE:1000000}"
        binders:
          paymentsConsumer-in-0:
            consumer:
              autoCommitOffset: "\${KAFKA_PAYMENTS_AUTO_COMMIT:\${KAFKA_CONSUMER_CONFIG_AUTO_COMMIT:true}}"
              configuration:
                connections.max.idle.ms: "\${KAFKA_PAYMENTS_REQUEST_CONNECTIONS_MAX_IDLE_MS:\${KAFKA_CONSUMER_CONFIG_CONNECTIONS_MAX_IDLE_MS:180000}}"
                max.poll:
                  interval.ms: "\${KAFKA_PAYMENTS_INTERVAL_TIMEOUT_MS:\${KAFKA_CONFIG_MAX_POLL_INTERVAL_TIMEOUT_MS:300000}}"
                  records: "\${KAFKA_PAYMENTS_MAX_POLL_SIZE:\${KAFKA_CONSUMER_CONFIG_MAX_POLL_SIZE:500}}"
                socket.connection.setup.timeout:
                  max.ms: "\${KAFKA_PAYMENTS_REQUEST_CONNECTION_TIMEOUT_MAX_MS:\${KAFKA_CONSUMER_CONFIG_CONNECTION_TIMEOUT_MAX_MS:200000}}"
                  ms: "\${KAFKA_PAYMENTS_REQUEST_CONNECTION_TIMEOUT_MS:\${KAFKA_CONSUMER_CONFIG_CONNECTION_TIMEOUT_MS:100000}}"
              standardHeaders: "\${KAFKA_PAYMENTS_STANDARD_HEADERS:\${KAFKA_CONSUMER_CONFIG_STANDARD_HEADERS:both}}"
              startOffset: "\${KAFKA_PAYMENTS_REQUEST_START_OFFSET:\${KAFKA_CONSUMER_CONFIG_START_OFFSET:earliest}}"
          dataEventsConsumer-in-0:
            consumer:
              autoCommitOffset: "\${KAFKA_DATA_EVENTS_AUTO_COMMIT:\${KAFKA_CONSUMER_CONFIG_AUTO_COMMIT:true}}"
              configuration:
                connections.max.idle.ms: "\${KAFKA_DATA_EVENTS_REQUEST_CONNECTIONS_MAX_IDLE_MS:\${KAFKA_CONSUMER_CONFIG_CONNECTIONS_MAX_IDLE_MS:180000}}"
                max.poll:
                  interval.ms: "\${KAFKA_DATA_EVENTS_INTERVAL_TIMEOUT_MS:\${KAFKA_CONFIG_MAX_POLL_INTERVAL_TIMEOUT_MS:300000}}"
                  records: "\${KAFKA_DATA_EVENTS_MAX_POLL_SIZE:\${KAFKA_CONSUMER_CONFIG_MAX_POLL_SIZE:500}}"
                socket.connection.setup.timeout:
                  max.ms: "\${KAFKA_DATA_EVENTS_REQUEST_CONNECTION_TIMEOUT_MAX_MS:\${KAFKA_CONSUMER_CONFIG_CONNECTION_TIMEOUT_MAX_MS:200000}}"
                  ms: "\${KAFKA_DATA_EVENTS_REQUEST_CONNECTION_TIMEOUT_MS:\${KAFKA_CONSUMER_CONFIG_CONNECTION_TIMEOUT_MS:100000}}"
              standardHeaders: "\${KAFKA_DATA_EVENTS_STANDARD_HEADERS:\${KAFKA_CONSUMER_CONFIG_STANDARD_HEADERS:both}}"
              startOffset: "\${KAFKA_DATA_EVENTS_REQUEST_START_OFFSET:\${KAFKA_CONSUMER_CONFIG_START_OFFSET:earliest}}"
          auditConsumer-in-0:
            consumer:
              autoCommitOffset: "\${KAFKA_AUDIT_AUTO_COMMIT:\${KAFKA_CONSUMER_CONFIG_AUTO_COMMIT:true}}"
              configuration:
                connections.max.idle.ms: "\${KAFKA_AUDIT_REQUEST_CONNECTIONS_MAX_IDLE_MS:\${KAFKA_CONSUMER_CONFIG_CONNECTIONS_MAX_IDLE_MS:180000}}"
                max.poll:
                  interval.ms: "\${KAFKA_AUDIT_INTERVAL_TIMEOUT_MS:\${KAFKA_CONFIG_MAX_POLL_INTERVAL_TIMEOUT_MS:300000}}"
                  records: "\${KAFKA_AUDIT_MAX_POLL_SIZE:\${KAFKA_CONSUMER_CONFIG_MAX_POLL_SIZE:500}}"
                socket.connection.setup.timeout:
                  max.ms: "\${KAFKA_AUDIT_REQUEST_CONNECTION_TIMEOUT_MAX_MS:\${KAFKA_CONSUMER_CONFIG_CONNECTION_TIMEOUT_MAX_MS:200000}}"
                  ms: "\${KAFKA_AUDIT_REQUEST_CONNECTION_TIMEOUT_MS:\${KAFKA_CONSUMER_CONFIG_CONNECTION_TIMEOUT_MS:100000}}"
              standardHeaders: "\${KAFKA_AUDIT_STANDARD_HEADERS:\${KAFKA_CONSUMER_CONFIG_STANDARD_HEADERS:both}}"
              startOffset: "\${KAFKA_AUDIT_REQUEST_START_OFFSET:\${KAFKA_CONSUMER_CONFIG_START_OFFSET:earliest}}"
management:
  info:
    build.enabled: true
    java.enabled: true
    git.enabled: true
  otlp.metrics.export.enabled: "\${TRACING_EXPORT:false}"
  tracing:
    sampling.probability: "\${TRACING_SAMPLING_PROBABILITY:1.0}"
    baggage.remote-fields:
      - X-user-id
  observations:
    http.server:
      filter.order: -100
  endpoints:
    jmx:
      exposure.include: "*"
    web:
      exposure:
        include: health, info, prometheus, metrics
      base-path: /actuator
  endpoint:
    health:
      probes.enabled: true
      logging.slow-indicator-threshold: "\${HEALTH_ACTUATOR_LOGGER_TIMEOUT_DURATION:PT1S}"
      show-details: "\${HEALTH_ACTUATOR_SHOW_DETAILS:when-authorized}"
      group:
        readiness.include: "*"
        liveness.include: livenessState,diskSpace,ping
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${artifactId}
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
    enable:
      jvm: true
      process: true
      system: true
      http: true
      logback: true

logging:
  level:
    root: "\${LOG_LEVEL_ROOT:INFO}"
    it.gov.pagopa: "\${LOG_LEVEL_PAGOPA:INFO}"
    org.springframework: "\${LOG_LEVEL_SPRING:INFO}"
    org.springframework.boot.availability: "\${LOG_LEVEL_SPRING_BOOT_AVAILABILITY:DEBUG}"
    org.springframework.kafka: "\${LOG_LEVEL_SPRING_KAFKA:INFO}"
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: "\${LOG_LEVEL_KAFKA_CONSUMER_COORDINATOR:WARN}"
    org.apache.kafka.clients.admin.internals.AdminMetadataManager: "\${LOG_LEVEL_KAFKA_ADMIN_METADATA_MANAGER:WARN}"
    org.springdoc.core.utils.SpringDocAnnotationsUtils: "\${LOG_LEVEL_SPRING_DOC:ERROR}"
    PERFORMANCE_LOG: "\${LOG_LEVEL_PERFORMANCE_LOG:INFO}"
    PERFORMANCE_LOG.API_REQUEST: "\${LOG_LEVEL_PERFORMANCE_LOG_API_REQUEST:\${logging.level.PERFORMANCE_LOG}}"
    PERFORMANCE_LOG.REST_INVOKE: "\${LOG_LEVEL_PERFORMANCE_LOG_REST_INVOKE:\${logging.level.PERFORMANCE_LOG}}"
    PERFORMANCE_LOG.INCOMING_EVENT: "\${LOG_LEVEL_PERFORMANCE_LOG_INCOMING_EVENT:\${logging.level.PERFORMANCE_LOG}}"

springdoc:
  api-docs.version: openapi_3_0
  writer-with-default-pretty-printer: true

springwolf:
  docket:
    base-package: it.gov.pagopa.analytics.ingestion.event
    info:
      title: "\${spring.application.name}"
      version: "\${spring.application.version}"
      description: AsyncAPI And Models
    servers.kafka-server:
      protocol: kafka
      host: "\${KAFKA_BINDER_BROKER:localhost:9093}"
  use-fqn: false

jwt:
  access-token:
    public-key: "\${JWT_TOKEN_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2ovm/rd3g69dq9PisinQ
                6mWy8ZttT8D+GKXCsHZycsGnN7b74TPyYy+4+h+9cgJeizp8RDRrufHjiBrqi/2r
                eOk/rD7ZHbpfQvHK8MYfgIVdtTxYMX/GGdOrX6/5TV2b8e2aCG6GmxF0UuEvxY9o
                TmcZUxnIeDtl/ixz4DQ754eS363qWfEA92opW+jcYzr07sbQtR86e+Z/s/CUeX6W
                1PHNvBqdlAgp2ecr/1DOLq1D9hEANBPSwbt+FM6FNe4vLphi7GTwiB0yaAuy+jE8
                odND6HPvvvmgbK1/2qTHn/HJjWUm11LUC73BszR32BKbdEEhxPQnnwswVekWzPi1
                IwIDAQAB
                -----END PUBLIC KEY-----}"

rest:
  defaults:
    connection-pool:
      size: "\${DEFAULT_REST_CONNECTION_POOL_SIZE:10}"
      size-per-route: "\${DEFAULT_REST_CONNECTION_POOL_SIZE_PER_ROUTE:5}"
      time-to-live-minutes: "\${DEFAULT_REST_CONNECTION_POOL_TIME_TO_LIVE_MINUTES:10}"
    timeout:
      connect-millis: "\${DEFAULT_REST_TIMEOUT_CONNECT_MILLIS:120000}"
      read-millis: "\${DEFAULT_REST_TIMEOUT_READ_MILLIS:120000}"

  auth:
    base-url: "\${AUTH_BASE_URL:http://localhost:8080/auth}"
    max-attempts: "\${AUTH_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${AUTH_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${AUTH_PRINT_BODY_WHEN_ERROR:true}"
    post-token:
      client_secret: "\${AUTH_CLIENT_SECRET:clientsecret}"

  debt-positions:
    base-url: "\${DEBT_POSITIONS_BASE_URL:http://localhost:8080/debtposition}"
    max-attempts: "\${DEBT_POSITIONS_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${DEBT_POSITIONS_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${DEBT_POSITIONS_PRINT_BODY_WHEN_ERROR:true}"

schedule:
  debt-position-type-orgs-ingestion:
    cron-expression: "\${SCHEDULE_DP_TYPE_ORGS_INGESTION_CRON:0 3 * * *}" # each day, 01:00-07:00-13:00-19:00 (Europe/Rome)

temporal:
  timeouts:
    system-info: "\${TEMPORAL_TIMEOUT_SYSTEM_INFO_SECONDS:5}"
    rpc-long-poll: "\${TEMPORAL_TIMEOUT_RPC_LONG_POLL_SECONDS:70}"
    rpc-query: "\${TEMPORAL_TIMEOUT_RPC_QUERY_SECONDS:10}"
    rpc-generic: "\${TEMPORAL_TIMEOUT_RPC_GENERIC_SECONDS:10}"

workflow:
  default:
    startToCloseTimeoutInSeconds: "\${DEFAULT_ACTIVITY_CONFIG_START_TO_CLOSE_TIMEOUT_IN_SECONDS:300}"
    retryInitialIntervalInMillis: "\${DEFAULT_ACTIVITY_CONFIG_RETRY_INITIAL_INTERVAL_IN_MILLIS:1000}"
    retryBackoffCoefficient: "\${DEFAULT_ACTIVITY_CONFIG_RETRY_BACKOFF_COEFFICIENT:1.5}"
    retryMaximumAttempts: "\${DEFAULT_ACTIVITY_CONFIG_RETRY_MAXIMUM_ATTEMPTS:30}"

  # data ingestion
  debt-position-type-orgs-ingestion:
    start-to-close-timeout-in-seconds: "\${DP_TYPE_ORGS_INGESTION_ACTIVITY_CONFIG_START_TO_CLOSE_TIMEOUT_IN_SECONDS:\${workflow.default.startToCloseTimeoutInSeconds}}"
    retry-initial-interval-in-millis: "\${DP_TYPE_ORGS_INGESTION_ACTIVITY_CONFIG_RETRY_INITIAL_INTERVAL_IN_MILLIS:\${workflow.default.retryInitialIntervalInMillis}}"
    retry-backoff-coefficient: "\${DP_TYPE_ORGS_INGESTION_ACTIVITY_CONFIG_RETRY_BACKOFF_COEFFICIENT:\${workflow.default.retryBackoffCoefficient}}"
    retry-maximum-attempts: "\${DP_TYPE_ORGS_INGESTION_ACTIVITY_CONFIG_RETRY_MAXIMUM_ATTEMPTS:\${workflow.default.retryMaximumAttempts}}"
